language: node_js

node_js: stable

git:
  quiet: true

cache:
  directories:
    - node_modules

branches:
  only:
    - /^dev\/.*$/
    - master

before_install:
  - sudo apt-get -y install sshpass

script:
  - ./config/deploy

after_success:
  - sshpass -p $SERVER_PWD scp -o StrictHostKeyChecking=no -r ./dist/* root@$SERVER_IP:/root/html/
