language: node_js

node_js: stable

git:
  quiet: true

cache:
  directories:
    - node_modules

branches:
  only:
    - /^dev\/.*$/
    - master

before_install:
  - sudo apt-get -y install sshpass

script:
  - npm run build

after_success:
  - ./config/deploy

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=b75b93dabc69b6f9b5f4ff8dac855930b75c812fcb44c4197eaac366e56fca84
