language: node_js

node_js:
  - '12'

git:
  quiet: true

branches:
  only:
    - /^dev\/.*$/
    - master

script:
  - npm run build

after_success:
  - echo $SERVER_PWD
  - sshpass -p $SERVER_PWD scp -o StrictHostKeyChecking=no -r ./dist/* root@$SERVER_IP:/root/html/
