language: node_js

node_js:
  - '12'

git:
  quiet: true

branches:
  only:
    - /^dev\/.*$/
    - master

script:
  - npm run build

after_success:
  - export SSHPASS=$SERVER_PWD
  - sshpass -e scp -P 29134 -o stricthostkeychecking=no -r ./dist/* root@$SERVER_IP:/root/html/
